import type { Locale, Widen } from "@/i18n/config";

/** Copy for the Events, Resources, Our Team and Photos pages. */
const en = {
  events: {
    metaTitle: "Events",
    metaDescription: "Open houses, family nights, community events and hiring days at STARS Academy in Batesville, Arkansas.",
    crumb: "Events",
    eyebrow: "Events",
    title: "Come see STARS in person.",
    lede: "Open houses, family nights and community events. Children are welcome unless we say otherwise.",
    upcomingTitle: "Upcoming events",
    emptyTitle: "No events are scheduled right now.",
    emptyBody: "We post open houses and family events here as soon as they’re planned. In the meantime, you’re always welcome to schedule a private tour.",
    emptyCta: "Schedule a tour",
    addToCalendar: "Add to calendar",
    addToCalendarFor: "Add “{title}” to your calendar",
    spanish: "Spanish interpretation available",
    allDay: "All day",
    registration: { none: "No sign-up needed", call: "Please call to save a spot:", link: "Sign up" },
    audience: { families: "For families", community: "Community", professionals: "For professionals", jobs: "Hiring" },
    location: { main: "STARS main campus", south: "STARS south campus", online: "Online", other: "" },
    teaserEyebrow: "Coming up",
    teaserTitle: "Upcoming events",
    teaserAll: "See all events",
  },
  resources: {
    metaTitle: "Resources for Families",
    metaDescription: "Handouts and trusted links for families: getting started at STARS, child development, activities at home, insurance and community support.",
    crumb: "Resources",
    eyebrow: "Resources",
    title: "Trusted help, in one place.",
    lede: "Handouts from our team and links we recommend to families. Questions about your own child? Call us. We’re glad to talk it through.",
    topicsNav: "Topics",
    topics: {
      "getting-started": "Getting started at STARS",
      development: "Child development & milestones",
      "at-home": "Activities at home",
      insurance: "Insurance & Medicaid",
      community: "Community support",
    },
    kind: { page: "On this site", pdf: "PDF", external: "External site" },
    inEnglish: "In English",
    inSpanish: "In Spanish",
    from: "From",
    opensNewTab: "(opens in a new tab)",
    disclaimer: "Links to other organizations are for information only. STARS isn’t responsible for their content.",
    nextTitle: "Have a question about your child?",
    nextBody: "Call us or send a message. We’ll help you find the right next step, whether or not it’s STARS.",
    nextCta: "Contact STARS",
    browseAll: "Browse all family resources",
  },
  team: {
    metaTitle: "Our Team",
    metaDescription: "Meet the therapists, nurses, educators and staff of STARS Academy, the pediatric day treatment program in Batesville, Arkansas.",
    crumb: "Our team",
    eyebrow: "Our team",
    title: "The people who make each day work.",
    lede: "Licensed therapists, nurses and early childhood educators share every classroom, so your child’s care is one plan, not five appointments.",
    disciplinesTitle: "Who your child works with",
    disciplines: [
      { name: "Early childhood developmental specialists", body: "Lead each classroom and build your child’s day around their developmental plan." },
      { name: "Speech-language pathologists", body: "Communication, language, feeding and swallowing, in English or Spanish." },
      { name: "Occupational therapists", body: "Fine motor skills, sensory processing and the everyday skills of play and self-care." },
      { name: "Physical therapists", body: "Movement, strength, balance and getting around the world with confidence." },
      { name: "Registered nurses", body: "Medications, tube feedings, oxygen, seizure plans and coordination with your child’s doctors." },
      { name: "Developmental technicians & van teams", body: "Extra hands in every classroom, and safe rides to and from STARS." },
    ],
    peopleTitle: "Meet our team",
    groups: {
      leadership: "Leadership",
      therapy: "Therapy",
      nursing: "Nursing",
      education: "Classrooms & education",
      support: "Transportation, office & support",
    },
    speaksSpanish: "Habla español",
    speaksSpanishLabel: "Speaks Spanish",
    joinTitle: "Want to join us?",
    joinBody: "We’re always glad to meet therapists, nurses and educators who love working with young children.",
    joinCta: "See open positions",
  },
  photos: {
    metaTitle: "Photos",
    metaDescription: "A look inside STARS Academy: classrooms, therapy, outdoor play and family events.",
    crumb: "Photos",
    eyebrow: "Photos",
    title: "A look inside STARS.",
    lede: "Classrooms, therapy and play. Every photo of a child here is shared with written permission from their family.",
    topics: { classrooms: "Classrooms", therapy: "Therapy", outdoors: "Outdoors & play", events: "Events", campus: "Our campus" },
    open: "View larger",
    close: "Close",
    previous: "Previous photo",
    next: "Next photo",
    counter: "Photo {n} of {total}",
    visitCta: "See it for yourself: schedule a tour",
  },
};

const es: Widen<typeof en> = {
  events: {
    metaTitle: "Eventos",
    metaDescription: "Puertas abiertas, noches para familias, eventos comunitarios y días de contratación en STARS Academy en Batesville, Arkansas.",
    crumb: "Eventos",
    eyebrow: "Eventos",
    title: "Venga a conocer STARS en persona.",
    lede: "Puertas abiertas, noches para familias y eventos comunitarios. Los niños son bienvenidos, salvo que indiquemos lo contrario.",
    upcomingTitle: "Próximos eventos",
    emptyTitle: "Por ahora no hay eventos programados.",
    emptyBody: "Publicamos aquí los días de puertas abiertas y los eventos para familias en cuanto los planeamos. Mientras tanto, siempre puede programar una visita privada.",
    emptyCta: "Programar una visita",
    addToCalendar: "Agregar al calendario",
    addToCalendarFor: "Agregar “{title}” a su calendario",
    spanish: "Habrá interpretación al español",
    allDay: "Todo el día",
    registration: { none: "No hace falta inscribirse", call: "Llame para reservar su lugar:", link: "Inscribirse" },
    audience: { families: "Para familias", community: "Comunidad", professionals: "Para profesionales", jobs: "Empleo" },
    location: { main: "Sede principal de STARS", south: "Sede sur de STARS", online: "En línea", other: "" },
    teaserEyebrow: "Próximamente",
    teaserTitle: "Próximos eventos",
    teaserAll: "Ver todos los eventos",
  },
  resources: {
    metaTitle: "Recursos para familias",
    metaDescription: "Materiales y enlaces de confianza para familias: cómo empezar en STARS, desarrollo infantil, actividades en casa, seguro médico y apoyo en la comunidad.",
    crumb: "Recursos",
    eyebrow: "Recursos",
    title: "Ayuda de confianza, en un solo lugar.",
    lede: "Materiales de nuestro equipo y enlaces que recomendamos a las familias. ¿Tiene preguntas sobre su hijo? Llámenos; con gusto lo hablamos.",
    topicsNav: "Temas",
    topics: {
      "getting-started": "Cómo empezar en STARS",
      development: "Desarrollo infantil",
      "at-home": "Actividades en casa",
      insurance: "Seguro médico y Medicaid",
      community: "Apoyo en la comunidad",
    },
    kind: { page: "En este sitio", pdf: "PDF", external: "Sitio externo" },
    inEnglish: "En inglés",
    inSpanish: "En español",
    from: "De",
    opensNewTab: "(se abre en una pestaña nueva)",
    disclaimer: "Los enlaces a otras organizaciones son solo informativos. STARS no es responsable de su contenido.",
    nextTitle: "¿Tiene preguntas sobre su hijo?",
    nextBody: "Llámenos o envíenos un mensaje. Le ayudaremos a encontrar el siguiente paso adecuado, sea o no STARS.",
    nextCta: "Contactar a STARS",
    browseAll: "Ver todos los recursos para familias",
  },
  team: {
    metaTitle: "Nuestro equipo",
    metaDescription: "Conozca a los terapeutas, enfermeras, educadores y personal de STARS Academy, el programa de tratamiento diurno pediátrico en Batesville, Arkansas.",
    crumb: "Nuestro equipo",
    eyebrow: "Nuestro equipo",
    title: "Las personas que hacen posible cada día.",
    lede: "Terapeutas, enfermeras y educadores de la primera infancia con licencia comparten cada salón, así que la atención de su hijo es un solo plan, no cinco citas.",
    disciplinesTitle: "Con quién trabaja su hijo",
    disciplines: [
      { name: "Especialistas en desarrollo de la primera infancia", body: "Dirigen cada salón y organizan el día de su hijo según su plan de desarrollo." },
      { name: "Patólogos del habla y lenguaje", body: "Comunicación, lenguaje, alimentación y deglución, en inglés o en español." },
      { name: "Terapeutas ocupacionales", body: "Motricidad fina, procesamiento sensorial y las habilidades diarias del juego y el cuidado personal." },
      { name: "Fisioterapeutas", body: "Movimiento, fuerza, equilibrio y desplazarse por el mundo con confianza." },
      { name: "Enfermeras registradas", body: "Medicamentos, alimentación por sonda, oxígeno, planes para convulsiones y coordinación con los médicos de su hijo." },
      { name: "Técnicos de desarrollo y equipos de transporte", body: "Manos extra en cada salón y viajes seguros de ida y vuelta a STARS." },
    ],
    peopleTitle: "Conozca a nuestro equipo",
    groups: {
      leadership: "Dirección",
      therapy: "Terapia",
      nursing: "Enfermería",
      education: "Salones y educación",
      support: "Transporte, oficina y apoyo",
    },
    speaksSpanish: "Habla español",
    speaksSpanishLabel: "Habla español",
    joinTitle: "¿Quiere unirse a nosotros?",
    joinBody: "Siempre nos alegra conocer a terapeutas, enfermeras y educadores a quienes les encanta trabajar con niños pequeños.",
    joinCta: "Ver puestos disponibles (en inglés)",
  },
  photos: {
    metaTitle: "Fotos",
    metaDescription: "Un vistazo a STARS Academy: salones, terapia, juego al aire libre y eventos para familias.",
    crumb: "Fotos",
    eyebrow: "Fotos",
    title: "Un vistazo a STARS.",
    lede: "Salones, terapia y juego. Cada foto de un niño se comparte con permiso por escrito de su familia.",
    topics: { classrooms: "Salones", therapy: "Terapia", outdoors: "Juego al aire libre", events: "Eventos", campus: "Nuestras instalaciones" },
    open: "Ver más grande",
    close: "Cerrar",
    previous: "Foto anterior",
    next: "Foto siguiente",
    counter: "Foto {n} de {total}",
    visitCta: "Véalo usted mismo: programe una visita",
  },
};

export const communityCopy: Record<Locale, Widen<typeof en>> = { en, es };
