import type { Locale, Widen } from "@/i18n/config";

const en = {
  metaTitle: "Getting Started — Eligibility, Funding & Enrollment",
  metaDescription:
    "Could STARS help your child? Who STARS serves, how day treatment is paid for (Medicaid, ARKids First-A, SSI, TEFRA) and the steps from first call to first day.",
  crumb: "Getting started",
  eyebrow: "Getting started",
  title: "Could STARS help your child? Let’s find out together.",
  lede: "You don’t need to have everything figured out before you contact us. This page explains who STARS serves, how services are paid for and what the steps look like — and our team will walk you through the rest.",
  sendInquiry: "Send an inquiry",
  fitEyebrow: "Is STARS a good fit?",
  fitTitle: "STARS may be right for your child if…",
  fitLede: "Any one of these is a good reason to call. You don’t need a diagnosis to ask a question.",
  eligibilityEyebrow: "Eligibility",
  eligibilityTitle: "Three things determine eligibility.",
  eligibilityLede: "We’ll help you with each one — including checking your coverage and coordinating with your child’s doctor.",
  payingLabel: "Paying for services:",
  payingPrefix: "Day treatment services are paid for through",
  payingBody: "STARS can contact your insurance provider to find out what therapy services your child’s plan covers.",
  processEyebrow: "The process",
  processTitle: "From first call to first day.",
  practicalEyebrow: "Practical details",
  practicalTitle: "Good to know.",
  practical: {
    hours: "Hours",
    transportation: "Transportation",
    transportationBody: "STARS operates clinic-owned vans that bring children to and from the clinic.",
    language: "Language",
    languageBody: "Speech-language evaluations and therapy are offered in Spanish.",
    medical: "Medical needs",
    medicalBody: "Full-time licensed nurses are on staff.",
    medicalLink: "Learn about nursing care",
  },
  inquiryEyebrow: "Start the conversation",
  inquiryTitle: "Tell us about your child.",
  inquiryLede: "Send a short inquiry and someone from our team will contact you. There’s no commitment — it’s simply the first step.",
  packetTitle: "Already spoken with our team?",
  packetBody: "If STARS has asked you to complete the enrollment inquiry packet, you can open it securely here.",
  packetLink: "Open the enrollment inquiry packet",
  submit: "Send my inquiry",
  messageHint:
    "A sentence or two is plenty — for example, “My 2-year-old isn’t talking much yet.” Please don’t include diagnoses or medical records.",
  faqEyebrow: "Questions families ask",
  faqTitle: "Frequently asked questions",
  faqAll: "See all FAQs",
  nextTitle: "The easiest next step? Come visit.",
  nextBody: "A tour is relaxed, with no commitment. You’ll see the classrooms, meet our team and get your questions answered in person.",
  nextTour: "Schedule a tour",
  nextServices: "Explore services",
  related: [
    { title: "Our approach", body: "How we help children feel safe, connected and understood." },
    { title: "Nursing care", body: "Care for children with medical needs." },
  ],
} as const;

const es = {
  metaTitle: "Cómo empezar: elegibilidad, financiamiento e inscripción",
  metaDescription:
    "¿Podría STARS ayudar a su hijo? A quién atiende STARS, cómo se paga el tratamiento diurno (Medicaid, ARKids First-A, SSI, TEFRA) y los pasos desde la primera llamada hasta el primer día.",
  crumb: "Cómo empezar",
  eyebrow: "Cómo empezar",
  title: "¿Podría STARS ayudar a su hijo? Averigüémoslo juntos.",
  lede: "No necesita tener todo resuelto antes de comunicarse con nosotros. Esta página explica a quién atiende STARS, cómo se pagan los servicios y cuáles son los pasos; nuestro equipo le guiará en todo lo demás.",
  sendInquiry: "Enviar una consulta",
  fitEyebrow: "¿Es STARS una buena opción?",
  fitTitle: "STARS puede ser adecuado para su hijo si…",
  fitLede: "Cualquiera de estas razones es suficiente para llamarnos. No necesita un diagnóstico para hacernos una pregunta.",
  eligibilityEyebrow: "Elegibilidad",
  eligibilityTitle: "Tres cosas determinan la elegibilidad.",
  eligibilityLede: "Le ayudaremos con cada una, incluida la revisión de su cobertura y la coordinación con el médico de su hijo.",
  payingLabel: "Cómo se pagan los servicios:",
  payingPrefix: "Los servicios de tratamiento diurno se pagan con",
  payingBody: "STARS puede comunicarse con su proveedor de seguro para saber qué servicios de terapia cubre el plan de su hijo.",
  processEyebrow: "El proceso",
  processTitle: "De la primera llamada al primer día.",
  practicalEyebrow: "Detalles prácticos",
  practicalTitle: "Bueno saber.",
  practical: {
    hours: "Horario",
    transportation: "Transporte",
    transportationBody: "STARS tiene camionetas propias que llevan a los niños al centro y de regreso.",
    language: "Idioma",
    languageBody: "Las evaluaciones y la terapia del habla y lenguaje se ofrecen en español.",
    medical: "Necesidades médicas",
    medicalBody: "Contamos con enfermeros con licencia de tiempo completo.",
    medicalLink: "Conozca nuestro servicio de enfermería",
  },
  inquiryEyebrow: "Inicie la conversación",
  inquiryTitle: "Cuéntenos sobre su hijo.",
  inquiryLede: "Envíe una consulta breve y alguien de nuestro equipo se comunicará con usted. No hay ningún compromiso: es simplemente el primer paso.",
  packetTitle: "¿Ya habló con nuestro equipo?",
  packetBody: "Si STARS le pidió completar el paquete de solicitud de inscripción, puede abrirlo de forma segura aquí.",
  packetLink: "Abrir el paquete de solicitud de inscripción",
  submit: "Enviar mi consulta",
  messageHint:
    "Con una o dos oraciones es suficiente; por ejemplo: “Mi hijo de 2 años todavía no habla mucho”. Por favor, no incluya diagnósticos ni expedientes médicos.",
  faqEyebrow: "Preguntas de las familias",
  faqTitle: "Preguntas frecuentes",
  faqAll: "Ver todas las preguntas",
  nextTitle: "¿El siguiente paso más fácil? Visítenos.",
  nextBody: "Las visitas son tranquilas y sin compromiso. Verá las aulas, conocerá a nuestro equipo y resolverá sus dudas en persona.",
  nextTour: "Programar una visita",
  nextServices: "Ver los servicios",
  related: [
    { title: "Nuestro enfoque", body: "Cómo ayudamos a los niños a sentirse seguros, conectados y comprendidos." },
    { title: "Enfermería", body: "Atención para niños con necesidades médicas." },
  ],
} as const satisfies Widen<typeof en>;

export const gettingStartedCopy: Record<Locale, Widen<typeof en>> = { en, es };
